### ISSUE TITLE
suitable for app store ?

### ISSUE THREAD

**Issue by weepy** [yenrab/SwiftlyHybrid#1]
hi there,

I was wondering if the temp hack was suitable for apps in production - i.e. submitting to the apple store ?

Also do you know if the temporary device-wide or only app-wide? 

Thanks !

Jonah

**Comment by yenrab** [comment]
Jonah,

There should be no problem submitting apps to the app store using this temp hack. It doesn’t do anything ‘unproved.’

The temporary location is app-wide.

Lee

**Comment by weepy** [comment]
great thanks!
