### ISSUE TITLE
Resizing / Orientation

### ISSUE THREAD

**Issue by andymans** [yenrab/SwiftlyHybrid#2]
To ensure proper handling of orientation change on iOS, I found that adding this line to the SwiflyMessageHandler's init function can help:

appWebView?.autoresizingMask = [.flexibleWidth, .flexibleHeight]

Previously (swift 3 and below) I was writing a ton of boilerplate to handle orientation; but one simple line seems to do the trick.

**Comment by yenrab** [comment]
Thanks andymans. I've added that code to the iOS file.
